# Generated by Django 5.1.3 on 2024-12-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('return_value', models.FloatField()),
                ('trades', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('best_trade', models.FloatField()),
                ('worst_trade', models.FloatField()),
                ('max_duration', models.CharField(max_length=100)),
                ('avg_duration', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('initial_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('stop_price', models.FloatField()),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('timeout', models.CharField(max_length=50)),
                ('investment', models.FloatField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
