# Generated by Django 5.1.3 on 2024-12-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_botsettings_alter_symbol_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_futuer',
            field=models.BooleanField(default=False),
        ),
    ]
