# Generated by Django 5.1.3 on 2024-12-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_trade_is_futuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('return_value', models.FloatField()),
                ('trades', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('best_trade', models.FloatField()),
                ('worst_trade', models.FloatField()),
                ('max_duration', models.CharField(max_length=100)),
                ('avg_duration', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
