# Generated by Django 5.1.4 on 2024-12-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_fsymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandlestickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('interval', models.CharField(default='1m', max_length=10)),
                ('open_time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quote_asset_volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('taker_buy_base_asset_volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('taker_buy_quote_asset_volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('number_of_trades', models.IntegerField()),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'interval', 'open_time'], name='apps_candle_symbol_16a34c_idx')],
                'unique_together': {('symbol', 'interval', 'open_time')},
            },
        ),
    ]
