# Generated by Django 5.1.3 on 2024-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_fsymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='description',
            field=models.TextField(default=1, help_text='description for settings what is do?'),
            preserve_default=False,
        ),
    ]
