# Generated by Django 5.1.3 on 2024-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_botsettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='for_futuer',
            field=models.BooleanField(default=False, help_text='valid for futuer bot and spot?'),
        ),
    ]
